### ISSUE TITLE
Rename "u-photo" to "u-image"

### ISSUE THREAD

**Issue by cweiske** [microformats/h-entry#1]
http://microformats.org/wiki/h-entry says:

> u-photo - one or more photos that is/are considered the primary content of the entry, unless there is a p-location h-card, which is still considered a "checkin" (i.e. with a photo). Otherwise the presence of a u-photo means the name of the entry should be interpreted as a caption on the photo, and the summary/content should be interpreted as a description of the photo.

Micropub follows h-entry here in allowing `photo`, `video` and `audio` file uploads.

Both `u-audio` and `u-video` are identical to `u-` + official MIME type media types, while `photo` is unprecedented.
To stay in line with MIME type media types, rename `u-photo` to `u-image`.

This would allow easier mapping of file types to microformat properties since one can simply use the mime type's media type (the string before the slash).

----
Related to w3c/Micropub#48

**Comment by kevinmarks** [comment]
Photo means more than just image, as is made clear in the  text. We also have u-featured for an image which is not necessarily  the core content of the entry, but is used as a thumbnail/preview. The photo/logo distinction is important too (which occur in h-card and h-feed)  and we reuse those names here for consistency.

**Comment by tantek** [comment]
Thanks @cweiske for raising the prior-art compat issue. In general microformats leans on the side of less invention / more re-use, so in any case where it appears there is some prior-art, and a microformats spec deliberately chooses something different, we need to document the why (which should be a good why).

@kevinmarks is right, for h-entry in particular, what drove the design/name of u-photo was the specific user-centric use-case of photo-posting, which we wanted to represent directly, rather than abstractly with a label like "image". In addition, also as noted by Kevin, "photo" was re-used from h-card, which re-used it from hCard/vCard, thus "photo" *has* precedent (is not unprecedented).

With the design iteration to microformats2 parsing and vocabularies, we've been greatly favoring (requiring) implementation / real world *user* use/benefits with additions, and this means that just because a prior spec/protocol/format has something similar, we should only re-use it if it maps directly.

mime-types are abstract plumbing that does not map directly to UX. thus they may not be the best source for re-use for microformats. On the contrary, something like vCard nearly directly maps to/from Address Book / Contact Card UX, and thus made/makes more sense for re-use/mapping per microformats principles etc.

Recommend closing without change per the above reasoning.
